image: registry.cloud.fits/fits/buildtools:1

stages:
    - build
    - push

merge-request:
    stage: build
    only:
      - merge_requests
    script: docker-make --Lint --summary --build-only metal-api-merge-request

# push:
#     stage: push
#     script: docker-make --Lint --summary --build-only metal-api-master
#     only:
#       - master
