image: registry.cloud.fits/fits/builder:7-dev

stages:
    - test
    - push

test:
    stage: test
    script: CGO_ENABLED=1 go test -cover ./...
    except:
       - prod

push:
    stage: push
    script: docker-make --exclude-linting-rules rule3 --summary
    only:
      - master
      - prod
