image: registry.cloud.fits/fits/builder:7

stages:
    - test
    - push

test:  
    stage: test
    script: make test-ci
    except:
      - prod

push:
    stage: push
    script: docker-make --exclude-linting-rules rule3 --summary
    only:
      - prod
