---
image: registry.cloud.fits/fits/buildtools:1

with-slug:
  script: docker-make -x rule2,rule3 --summary --build-only metal-api-slug
  only:
    - merge_requests
    - tags

master:
    script: docker-make -x rule2,rule3 --summary --build-only metal-api-master
    only:
      - master
