version: '2'

networks:
  appl:
    driver: bridge

services:
  swagger:
    image: swaggerapi/swagger-ui
    networks:
      - appl
    ports:
     - "9090:8080"
    environment:
      - API_URL=http://localhost:8080/apidocs.json

  metal-api:
    tty: true
    networks:
      - appl
    build:
      context: .
    image: registry.fi-ts.io/metal/metal-api
    ports:
      - "8080:8080"
    environment:
      METAL_API_WITH_MOCK_DATA: "true"
      METAL_API_BIND_ADDR: 0.0.0.0
