version: '2'

networks:
  appl:
    driver: bridge


services:
  swagger:
    image: swaggerapi/swagger-ui
    networks:
      - appl
    ports:
     - "9090:8080"
    environment:
      - API_URL=http://localhost:8080/apidocs.json

  maas-api:
    networks:
      - appl
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MAAS_API_BIND_ADDR: 0.0.0.0
    command: /maas-api
