swagger: "2.0"
info:
  description: "Proxy server for the metal project to communicate with netbox using pynetbox."
  version: "1.0.0"
  title: "Netbox API Proxy"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "devops@f-i-ts.de"
  license:
    name: "MIT"
    url: "http://mit.org"
basePath: "/api/v1"
tags:
- name: "machines"
  description: "Endpoints for managing machines in the netbox"
- name: "switches"
  description: "Endpoints for managing switches in the netbox"
schemes:
- "http"
securityDefinitions:
  Bearer:
    in: "header"
    name: "Authorization"
    type: "apiKey"
    x-apikeyInfoFunc: "netbox_api_proxy.api.api_key_auth"
security:
- Bearer: []
paths:
  /machines/{uuid}/register:
    post:
      tags:
      - "machines"
      summary: "Register a new machine"
      description: "Register a new machine to the netbox"
      operationId: "netbox_api_proxy.api.machine_register"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "application/problem+json"
      parameters:
      - $ref: "#/parameters/MachineUUID"
      - name: "request"
        in: "body"
        description: "The machine registration body"
        required: true
        schema:
          $ref: "#/definitions/MachineRegistrationRequest"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Problem"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Problem"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Problem"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Problem"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Problem"
  /machines/{uuid}/allocate:
    post:
      tags:
      - "machines"
      summary: "Allocate a machine"
      description: "Allocated a registered machine for a tenant"
      operationId: "netbox_api_proxy.api.machine_allocate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "application/problem+json"
      parameters:
      - $ref: "#/parameters/MachineUUID"
      - name: "request"
        in: "body"
        description: "The machine allocation body"
        required: true
        schema:
          $ref: "#/definitions/MachineAllocationRequest"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/MachineAllocationResponse"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Problem"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Problem"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Problem"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Problem"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Problem"
  /machines/{uuid}/release:
    post:
      tags:
      - "machines"
      summary: "Releases a machine"
      description: "Releases an allocated machine"
      operationId: "netbox_api_proxy.api.machine_release"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "application/problem+json"
      parameters:
      - $ref: "#/parameters/MachineUUID"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Problem"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Problem"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Problem"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Problem"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Problem"
  /switches/{uuid}/register:
    post:
      tags:
      - "switches"
      summary: "Register a new switch"
      description: "Register a new switch to the netbox"
      operationId: "netbox_api_proxy.api.switch_register"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "application/problem+json"
      parameters:
      - $ref: "#/parameters/MachineUUID"
      - name: "request"
        in: "body"
        description: "The switch registration body"
        required: true
        schema:
          $ref: "#/definitions/SwitchRegistrationRequest"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Problem"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Problem"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Problem"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Problem"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Problem"
parameters:
  MachineUUID:
    in: "path"
    name: "uuid"
    description: "The product serial of the machine (unique identifier of this machine)"
    type: "string"
    required: true
definitions:
  MachineRegistrationRequest:
    type: "object"
    required:
    - "size"
    - "partition"
    - "rack"
    - "nics"
    properties:
      size:
        description: "The size of the machine"
        type: "string"
        minLength: 1
      partition:
        description: "The id of the partition"
        type: "string"
        minLength: 1
      rack:
        description: "The name of the rack"
        type: "string"
        minLength: 1
      nics:
        description: "The network interfaces of this machine"
        type: "array"
        items:
          $ref: "#/definitions/Nic"
  MachineAllocationRequest:
    type: "object"
    required:
    - "name"
    - "tenant"
    - "vrf"
    - "project"
    properties:
      name:
        description: "The desired name for this machine in the netbox"
        type: "string"
        minLength: 1
      tenant:
        description: "The name of the tenant to assign this machine to"
        type: "string"
        minLength: 1
      vrf:
        description: "The name of the vrf to assign this machine to"
        type: "string"
        minLength: 1
      project:
        description: "The name of the project to assign this machine to"
        type: "string"
        minLength: 1
      os:
        description: "The operating system name that will be installed on this machine"
        type: "string"
        minLength: 1
      description:
        description: "Additional description for this machine in the netbox"
        type: "string"
        minLength: 1
  MachineAllocationResponse:
    type: "object"
    required:
    - "cidr"
    properties:
      cidr:
        description: "The allocated cidr of the allocated machine"
        type: "string"
  Nic:
    type: "object"
    required:
    - "name"
    - "mac"
    properties:
      name:
        description: "The name of the network interface"
        type: "string"
        minLength: 1
      mac:
        description: "The mac address of the network interface"
        type: "string"
        minLength: 1
  SwitchRegistrationRequest:
    type: "object"
    required:
    - "name"
    - "partition"
    - "rack"
    - "nics"
    properties:
      name:
        description: "The desired name for this machine in the netbox"
        type: "string"
        minLength: 1
      partition:
        description: "The id of the partition"
        type: "string"
        minLength: 1
      rack:
        description: "The name of the rack"
        type: "string"
        minLength: 1
      nics:
        description: "The network interfaces of this machine"
        type: "array"
        items:
          $ref: "#/definitions/Nic"
  Problem:
    type: "object"
    properties:
      type:
        type: "string"
        format: "uri"
        description: |
          An absolute URI that identifies the problem type.  When dereferenced,
          it SHOULD provide human-readable documentation for the problem type
          (e.g., using HTML).
        default: "about:blank"
      title:
        type: "string"
        description: |
          A short, summary of the problem type. Written in english and readable
          for engineers (usually not suited for non technical stakeholders and
          not localized); example: Service Unavailable
      status:
        type: "integer"
        format: "int32"
        description: |
          The HTTP status code generated by the origin server for this occurrence
          of the problem.
        minimum: 100
        maximum: 600
        exclusiveMaximum: true
        example: 503
      detail:
        type: "string"
        description: |
          A human readable explanation specific to this occurrence of the
          problem.
        example: "Connection to database timed out"
      instance:
        type: "string"
        format: "uri"
        description: |
          An absolute URI that identifies the specific occurrence of the problem.
          It may or may not yield further information if dereferenced.
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
