---
dev_setup: true

images:
  metal_api:
    image: registry.fi-ts.io/metal/metal-api
    tag: latest
    dex_addr: https://dex.test.fi-ts.io/dex
  nsq:
    image: nsqio/nsq
    tag: v1.1.0
  rethinkdb:
    image: rethinkdb
    tag: latest
  swagger_ui:
    image: swaggerapi/swagger-ui
    tag: latest

ports:
  metal_api: 8080
  rethinkdb: 28015
  rethinkdb_ui: 10080
  swagger_ui: 9090

metal_api:
  replicas: 1
  partitions: []
  sizes: []
  images: []

postgres:
  backup:
    s3:
      access_key: ""
      secret_key: ""
