---
dev_setup: true

images:
  metal_api:
    image: registry.fi-ts.io/metal/metal-api
    tag: latest
  nsq:
    image: nsqio/nsq
    tag: v1.1.0
  rethinkdb:
    image: rethinkdb
    tag: latest
  netbox:
    image: ninech/netbox
    tag: v2.4.8
  netbox_nginx:
    image: nginx
    tag: 1.15-alpine
  netbox_api_proxy:
    image: registry.fi-ts.io/metal/netbox-api-proxy
    tag: 0.4.1
  netbox_postgres:
    image: postgres
    tag: 11-alpine
  netbox_init_config:
    image: registry.fi-ts.io/metal/netbox-init-config
    tag: latest
  swagger_ui:
    image: swaggerapi/swagger-ui
    tag: latest

ports:
  metal_api: 8080
  rethinkdb: 28015
  rethinkdb_ui: 10080
  swagger_ui: 9090
  netbox: 8001
  netbox_nginx: 8000
  netbox_postgres: 5432
  netbox_api_proxy: 8002

metal_api:
  replicas: 1
  partitions: []
  sizes: []
  images: []

netbox:
  initializers:
    custom_fields: ""
    devices: "{      \"device_types\": [        {          \"manufacturer\": \"supermicro\",          \"model\": \"MBI-6219G-T7LX\",          \"slug\": \"c1-medium-x86\",          \"height\": 0,          \"parent_child_status\": \"child\",          \"tags\": [            \"allocatable\"          ]        },        {          \"manufacturer\": \"supermicro\",          \"model\": \"SYS-2029BT-HNTR (3)\",          \"slug\": \"s1-large-x86\",          \"height\": 0,          \"parent_child_status\": \"child\",          \"tags\": [            \"allocatable\"          ]        },        {          \"manufacturer\": \"supermicro\",          \"model\": \"SYS-2029BT-HNTR\",          \"slug\": \"c1-large-x86\",          \"height\": 0,          \"parent_child_status\": \"child\",          \"tags\": [            \"allocatable\"          ]        },        {          \"manufacturer\": \"supermicro\",          \"model\": \"SYS-2029BT-HNTR (2)\",          \"slug\": \"c1-xlarge-x86\",          \"height\": 0,          \"parent_child_status\": \"child\",          \"tags\": [            \"allocatable\"          ]        },        {          \"manufacturer\": \"supermicro\",          \"model\": \"MBI-6418A-T5H\",          \"slug\": \"t1-small-x86\",          \"height\": 0,          \"parent_child_status\": \"child\",          \"tags\": [            \"allocatable\"          ]        },        {          \"manufacturer\": \"vagrant\",          \"model\": \"libvirt-kvm\",          \"slug\": \"v1-small-x86\",          \"height\": 0,          \"parent_child_status\": \"child\",          \"tags\": [            \"allocatable\"          ]        },        {          \"manufacturer\": \"supermicro\",          \"model\": \"unknown\",          \"slug\": \"unknown\",          \"height\": 0,          \"parent_child_status\": null        },        {          \"manufacturer\": \"supermicro\",          \"model\": \"MBE-314E-416\",          \"slug\": \"MBE-314E-416\",          \"height\": 3,          \"parent_child_status\": \"parent\"        },        {          \"manufacturer\": \"edge-core\",          \"model\": \"AS7712-32X\",          \"slug\": \"AS7712-32X\",          \"height\": 1,          \"parent_child_status\": null        },        {          \"manufacturer\": \"edge-core\",          \"model\": \"AS4610-54P\",          \"slug\": \"AS4610-54P\",          \"height\": 1,          \"parent_child_status\": null        }      ],      \"device_roles\": [        {          \"name\": \"Switch\",          \"slug\": \"switch\",          \"color\": \"ff0000\"        },        {          \"name\": \"Blade Chassis\",          \"slug\": \"blade-chassis\",          \"color\": \"0090ff\"        },        {          \"name\": \"Server\",          \"slug\": \"server\",          \"color\": \"ff7200\"        }      ],      \"devices\": [        {          \"name\": \"Blade Chassis 1\",          \"device_type\": \"MBE-314E-416\",          \"device_role\": \"blade-chassis\",          \"site\": \"vagrant-lab\",          \"rack\": \"Vagrant Rack 1\",          \"face\": \"front\",          \"position\": 1,          \"bays\": 14        }      ]    }"
    groups: "{   \"metal\": {     \"users\": [       \"metal_api\"     ]   } }"
    ipam: "{\"prefixes\": [{\"prefix\": \"10.0.0.0/12\",\"status\": \"active\",\"is_a_pool\": true,\"site\": \"vagrant-lab\"}]}"
    manufacturer: "[   {     \"name\": \"Supermicro\",     \"slug\": \"supermicro\"   },   {     \"name\": \"Edgecore\",     \"slug\": \"edge-core\"   },   {     \"name\": \"Vagrant\",     \"slug\": \"vagrant\"   } ]"
    racks: "{ \"rack_groups\": [ { \"name\": \"Vagrant Racks\", \"slug\": \"vagrant-racks\",\"site\": \"vagrant-lab\",\"racks\": [{\"name\": \"Vagrant Rack 1\",\"height\": 10}]}]}"
    secrets: ""
    sites: "[ { \"name\": \"Vagrant Lab\", \"slug\": \"vagrant-lab\", \"physical_address\": \"Your Notebook!\", \"status\": \"active\" }]"
    tenants: "{  \"tenant_groups\": [{\"name\": \"metal\",\"slug\": \"metal\",\"tenants\": [ {\"name\": \"devops\",\"slug\": \"devops\",\"description\": \"Devops users of Metal\"}]}]}"
    users: "{   \"metal_api\": {     \"api_token\": \"9282895864c78f3dba1608e9c4cb37e55b2f9e97\",     \"permissions\": [       \"add_device\",       \"change_device\",       \"delete_device\",       \"add_interface\",       \"change_interface\",       \"add_tenant\",       \"add_tenantgroup\",       \"add_vrf\",       \"change_vrf\",       \"delete_vrf\",       \"add_prefix\",       \"change_prefix\",       \"delete_prefix\",       \"add_ipaddress\",       \"change_ipaddress\",       \"delete_ipaddress\",       \"add_secret\",       \"change_secret\",       \"delete_secret\"     ]   } }"

postgres:
  backup:
    s3:
      access_key: ""
      secret_key: ""
